[project]
name = "fastex"
version = "0.1.0"
description = "Fastex — lightweight extensions and utilities for building FastAPI applications faster."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
